---
networks:
  eden:
    external: true
services:
  zookeeper-sasl-1:
    image: confluentinc/cp-zookeeper:latest
    # This is required because Zookeeper can fail if kerberos is still initializing.
    restart: on-failure:3
    container_name: zk-sasl-1
    networks:
      - eden
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-sasl-1:22888:23888;zk-sasl-2:32888:33888;zk-sasl-3:42888:43888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_1_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dsun.security.krb5.debug=true
    volumes:
    - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
    # ports:
    #  - '22181:22181'
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-sasl-2:
    image: confluentinc/cp-zookeeper:latest
    # This is required because Zookeeper can fail if kerberos is still initializing.
    restart: on-failure:3
    container_name: zk-sasl-2
    networks:
      - eden
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-sasl-1:22888:23888;zk-sasl-2:32888:33888;zk-sasl-3:42888:43888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_2_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dsun.security.krb5.debug=true
    volumes:
    - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
    # ports:
    #   - '32181:32181'
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-sasl-3:
    image: confluentinc/cp-zookeeper:latest
    # This is required because Zookeeper can fail if kerberos is still initializing.
    restart: on-failure:3
    container_name: zk-sasl-3
    networks:
      - eden
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-sasl-1:22888:23888;zk-sasl-2:32888:33888;zk-sasl-3:42888:43888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_3_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dsun.security.krb5.debug=true
    volumes:
    - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
    # ports:
    #   - '42181:42181'
    extra_hosts:
      - "moby:127.0.0.1"

#  kerberos:
#    image: confluentinc/cp-kerberos:latest
#    network_mode: host
#    environment:
#      BOOTSTRAP: 0
#    volumes:
#      - ${KAFKA_SASL_SECRETS_DIR}:/tmp/keytab
#      - /dev/urandom:/dev/random
#    extra_hosts:
#      - "moby:127.0.0.1"

  kafka-sasl-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-sasl-1
    networks:
      - eden
    ports:
      - '19094:19094'
    # This is required because Kafka can fail if kerberos is still initializing.
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk-sasl-1:22181,zk-sasl-2:32181,zk-sasl-3:42181
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-sasl-1.eden:19094
      KAFKA_SSL_KEYSTORE_FILENAME: ssl/kafka.kafka-sasl-1.eden.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ssl/kafka-sasl-1.eden_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: ssl/kafka-sasl-1.eden_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: ssl/kafka.kafka-sasl-1.eden.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ssl/kafka-sasl-1.eden_truststore_creds
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker1_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dsun.security.krb5.debug=false
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-sasl-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-sasl-2
    networks:
      - eden
    ports:
      - '29094:29094'
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk-sasl-1:22181,zk-sasl-2:32181,zk-sasl-3:42181
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-sasl-2.eden:29094
      KAFKA_SSL_KEYSTORE_FILENAME: ssl/kafka.kafka-sasl-2.eden.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ssl/kafka-sasl-2.eden_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: ssl/kafka-sasl-2.eden_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: ssl/kafka.kafka-sasl-2.eden.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ssl/kafka-sasl-2.eden_truststore_creds
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker2_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dsun.security.krb5.debug=false
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-sasl-3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-sasl-3
    networks:
      - eden
    ports:
      - '39094:39094'
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk-sasl-1:22181,zk-sasl-2:32181,zk-sasl-3:42181
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-sasl-3.eden:39094
      KAFKA_SSL_KEYSTORE_FILENAME: ssl/kafka.kafka-sasl-3.eden.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ssl/kafka-sasl-3.eden_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: ssl/kafka-sasl-3.eden_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: ssl/kafka.kafka-sasl-3.eden.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ssl/kafka-sasl-3.eden_truststore_creds
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker3_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dsun.security.krb5.debug=false
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
    extra_hosts:
      - "moby:127.0.0.1"
