KafkaServer {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/broker3s.keytab"
    principal="kafka/kafka-sasl-3.eden@TEST.CONFLUENT.IO";
};
KafkaClient {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/broker3c.keytab"
    principal="kafka/kafka-sasl-3@TEST.CONFLUENT.IO";
};
Client {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/zkclient3.keytab"
    principal="zkclient/zk-sasl-3@TEST.CONFLUENT.IO";
};
