KafkaServer {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/broker2s.keytab"
    principal="kafka/kafka-sasl-2.eden@TEST.CONFLUENT.IO";
};
KafkaClient {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/broker2c.keytab"
    principal="kafka/kafka-sasl-2@TEST.CONFLUENT.IO";
};
Client {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/zkclient2.keytab"
    principal="zkclient/zk-sasl-2@TEST.CONFLUENT.IO";
};
