KafkaServer {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/broker1s.keytab"
    principal="kafka/kafka-sasl-1.eden@TEST.CONFLUENT.IO";
};
KafkaClient {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/broker1c.keytab"
    principal="kafka/kafka-sasl-1@TEST.CONFLUENT.IO";
};
Client {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/zkclient1.keytab"
    principal="zkclient/zk-sasl-1@TEST.CONFLUENT.IO";
};
