KafkaClientLO {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true

    keyTab="/etc/kafka/secrets/sasl/producer1.keytab"
    principal="producer1/kafka-sasl-lo@TEST.CONFLUENT.IO";
};

KafkaClientEN0 {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true

    keyTab="/etc/kafka/secrets/sasl/producer2.keytab"
    principal="producer2/kafka-sasl-en0@TEST.CONFLUENT.IO";
};
