Server {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/zk3.keytab"
    principal="zookeeper/zk-sasl-3.eden@TEST.CONFLUENT.IO";
};
Client {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/zkclient3.keytab"
    principal="zkclient/zk-sasl-3@TEST.CONFLUENT.IO";
};
