Server {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/zk2.keytab"
    principal="zookeeper/zk-sasl-2.eden@TEST.CONFLUENT.IO";
};
Client {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/zkclient2.keytab"
    principal="zkclient/zk-sasl-2@TEST.CONFLUENT.IO";
};
