Server {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/localhost.keytab"
    principal="zookeeper/localhost@TEST.CONFLUENT.IO";
};
Client {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/sasl/zkclient3.keytab"
    principal="zkclient/kafka-sasl@TEST.CONFLUENT.IO";
};
