ssl.enabled.protocols=TLSv1.2
ssl.keystore.location = /etc/kafka/secrets/ssl/kafka.consumer.keystore.jks
ssl.keystore.password = confluent
ssl.key.password=confluent
ssl.keystore.type = JKS
ssl.truststore.location = /etc/kafka/secrets/ssl/kafka.consumer.truststore.jks
ssl.truststore.password = confluent
ssl.truststore.type = JKS
ssl.protocol=TLSv1.2
security.protocol=SASL_SSL
sasl.mechanism=GSSAPI
sasl.kerberos.service.name=kafka
#sasl.jaas.config.file = /etc/kafka/secrets/consumer_jaas.conf
