ssl.enabled.protocols=TLSv1.2
ssl.keystore.location = /etc/kafka/secrets/ssl/kafka.producer.keystore.jks
ssl.keystore.password = confluent
ssl.key.password=confluent
ssl.keystore.type = JKS
ssl.truststore.location = /etc/kafka/secrets/ssl/kafka.producer.truststore.jks
ssl.truststore.password = confluent
ssl.truststore.type = JKS
ssl.protocol=TLSv1.2
security.protocol=SASL_SSL
sasl.mechanism=GSSAPI
sasl.kerberos.service.name=kafka
#sasl.jaas.config.file = /etc/kafka/secrets/producer_jaas.conf
#sasl.jaas.config={ \
#  com.sun.security.auth.module.Krb5LoginModule required \
#  useKeyTab=true \
#  storeKey=true \
#  keyTab="/etc/kafka/secrets/sasl/producer1.keytab" \
#  principal="producer1/kafka-sasl-en0@TEST.CONFLUENT.IO"; \
#};
